# Generated by Django 3.0.2 on 2020-01-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ORMMarketChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changeInTotalMarketCapPer', models.DecimalField(decimal_places=8, max_digits=28)),
                ('changeInTotalMarketCapUSD', models.DecimalField(decimal_places=8, max_digits=30)),
            ],
        ),
        migrations.CreateModel(
            name='ORMMarketSnapShot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalMarketCapUSD', models.DecimalField(decimal_places=8, max_digits=28)),
                ('totalBitcoinMarketCapUSD', models.DecimalField(decimal_places=8, max_digits=28)),
                ('totalAltsMarketCapUSD', models.DecimalField(decimal_places=8, max_digits=28)),
                ('bitcoinDominancePer', models.DecimalField(decimal_places=8, max_digits=28)),
                ('altsDominancePer', models.DecimalField(decimal_places=8, max_digits=28)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
