# Generated by Django 3.0.2 on 2020-01-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoMarketReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalMarketCapUSD', models.DecimalField(decimal_places=8, max_digits=28)),
                ('totalBitcoinMarketCapUSD', models.DecimalField(decimal_places=8, max_digits=28)),
                ('totalAltsMarketCapUSD', models.DecimalField(decimal_places=8, max_digits=28)),
                ('bitcoinDominancePer', models.DecimalField(decimal_places=8, max_digits=28)),
                ('altsDominancePer', models.DecimalField(decimal_places=8, max_digits=28)),
                ('changeInTotalMarketCapPer', models.DecimalField(decimal_places=8, max_digits=28)),
                ('changeInTotalMarketCapUSD', models.DecimalField(decimal_places=8, max_digits=28)),
                ('changeInBitcoinMarketCapPer', models.DecimalField(decimal_places=8, max_digits=28)),
                ('changeInBitcoinMarketCapUSD', models.DecimalField(decimal_places=8, max_digits=28)),
                ('changeInAltsMarketCapPer', models.DecimalField(decimal_places=8, max_digits=28)),
                ('changeInAltsMarketCapUSD', models.DecimalField(decimal_places=8, max_digits=28)),
            ],
        ),
    ]
